export const selfmailPalette = {
  ink: "#0f172a",
  canvas: "#f8fafc",
  muted: "#e2e8f0",
  line: "#cbd5e1",
  primary: "#2563eb",
  primaryForeground: "#eff6ff",
  accent: "#0f766e",
  accentForeground: "#f0fdfa",
  danger: "#dc2626",
  dangerForeground: "#fef2f2",
} as const;

export const selfmailTokens = {
  light: {
    background: selfmailPalette.canvas,
    foreground: selfmailPalette.ink,
    card: "#ffffff",
    cardForeground: selfmailPalette.ink,
    popover: "#ffffff",
    popoverForeground: selfmailPalette.ink,
    primary: selfmailPalette.primary,
    primaryForeground: selfmailPalette.primaryForeground,
    secondary: "#eff6ff",
    secondaryForeground: "#1e3a8a",
    muted: "#f1f5f9",
    mutedForeground: "#475569",
    accent: selfmailPalette.accent,
    accentForeground: selfmailPalette.accentForeground,
    destructive: selfmailPalette.danger,
    destructiveForeground: selfmailPalette.dangerForeground,
    border: selfmailPalette.line,
    input: selfmailPalette.line,
    ring: "#60a5fa",
  },
  dark: {
    background: "#020617",
    foreground: "#e2e8f0",
    card: "#0f172a",
    cardForeground: "#e2e8f0",
    popover: "#0f172a",
    popoverForeground: "#e2e8f0",
    primary: "#60a5fa",
    primaryForeground: "#0f172a",
    secondary: "#1e293b",
    secondaryForeground: "#e2e8f0",
    muted: "#111827",
    mutedForeground: "#94a3b8",
    accent: "#14b8a6",
    accentForeground: "#042f2e",
    destructive: "#f87171",
    destructiveForeground: "#450a0a",
    border: "#1e293b",
    input: "#1e293b",
    ring: "#93c5fd",
  },
} as const;

export type SelfmailPalette = typeof selfmailPalette;
export type SelfmailThemeTokens = typeof selfmailTokens.light;
