# Docker Compose file which expects that api, webservices and payments queue is running in the cloud.
# That means, we have only the smtp stuff left.

services:
  smtp:
    build:
      context: .
      dockerfile: apps/smtp/Dockerfile
      args:
        - CERTIFICATE_PATH=${CERTIFICATE_PATH}
    container_name: selfmail-smtp
    restart: unless-stopped
    ports:
      - "25:25"   # SMTP inbound
      - "587:587" # SMTP outbound (submission)
    depends_on:
      - rspamd
      - clamav
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}
      - SMTP_API_URL=http://selfmail-smtp-api:4001
      - RSPAMD_HOST=rspamd
      - RSPAMD_PORT=11332
      - CERTIFICATE_PATH=${CERTIFICATE_PATH}
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
      - DATABASE_URL=${DATABASE_URL}
      # For example Europe/Berlin
      - TZ=${TZ}
    networks:
      - default
    # Required for binding to privileged ports
    privileged: false
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./certs:${CERTIFICATE_PATH}:ro

  relay:
    build:
      context: .
      dockerfile: apps/relay/Dockerfile
    container_name: selfmail-relay
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - queue
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_URL=${REDIS_URL}
      - TZ=${TZ}
    networks:
      - default

  smtp-api:
    build:
      context: .
      dockerfile: apps/smtp-api/Dockerfile
    container_name: selfmail-smtp-api
    restart: unless-stopped
    ports:
      - "4001:4001"
    depends_on:
      - clamav
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
      - TZ=${TZ}
    networks:
      - default

  transactional-queue:
    build:
      context: .
      dockerfile: apps/transactional-queue/Dockerfile
    container_name: selfmail-transactional-queue
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}
      - TZ=${TZ}
    networks:
      - default
  queue:
    build:
      context: .
      dockerfile: apps/queue/Dockerfile
    container_name: selfmail-queue
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - TZ=${TZ}
    networks:
      - default
  rspamd:
    image: rspamd/rspamd:latest
    container_name: rspamd
    restart: unless-stopped
    ports:
      - "11332:11332" # Proxy/Milter
      - "11333:11333" # HTTP/JSON API
      - "11334:11334" # Web UI
    volumes:
      - ./rspamd/etc:/etc/rspamd
      - ./rspamd/var:/var/lib/rspamd
    environment:
      - TZ=${TZ}

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    restart: unless-stopped
    ports:
      - "3310:3310"
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: selfmail-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}

      - ACTIVATE_PAYMENTS=${ACTIVATE_PAYMENTS}
      - POLAR_SELFMAIL_PLUS_ID=${POLAR_SELFMAIL_PLUS_ID}
      - POLAR_SELFMAIL_PREMIUM_ID=${POLAR_SELFMAIL_PREMIUM_ID}
      - POLAR_WEBHOOK_SECRET=${POLAR_WEBHOOK_SECRET}
      - POLAR_ORG_SLUG=${POLAR_ORG_SLUG}
      - POLAR_SUCCESS_BASE_URL=${POLAR_SUCCESS_BASE_URL}

      - ENABLE_S3_UPLOAD=${ENABLE_S3_UPLOAD}
      - ENABLE_DOCKER_VOLUME_UPLOAD=${ENABLE_DOCKER_VOLUME_UPLOAD}

      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TZ=${TZ}
    ports:
      - "3010:3000"
    networks:
      - default
  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    container_name: selfmail-dashboard
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "4173:4173"
    networks:
      - default

volumes:
  rspamd-var:
  rspamd-etc:
  certs: