services:
  rspamd:
    image: rspamd/rspamd:latest
    container_name: rspamd
    restart: unless-stopped
    ports:
      - "11332:11332" # Proxy/Milter
      - "11333:11333" # HTTP/JSON API
      - "11334:11334" # Web UI
    volumes:
      - ./rspamd/etc:/etc/rspamd
      - ./rspamd/var:/var/lib/rspamd
    environment:
      - TZ=${TZ}

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    restart: unless-stopped
    ports:
      - "3310:3310"

  
  postgres:
    image: postgres:16
    container_name: selfmail-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  redis:
    image: redis:7
    container_name: selfmail-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  queue:
    build:
      context: .
      dockerfile: apps/queue/Dockerfile
    container_name: selfmail-queue
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=production
      - REDIS_HOST=selfmail-redis
      - REDIS_PORT=6379
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@selfmail-postgres:5432/${POSTGRES_DB}
      - TZ=${TZ}
    networks:
      - default

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: selfmail-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@selfmail-postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=selfmail-redis
      - REDIS_PORT=6379
      - TZ=${TZ}
    networks:
      - default

  payments:
    build:
      context: .
      dockerfile: apps/payments/Dockerfile
    container_name: selfmail-payments
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=production
      - REDIS_HOST=selfmail-redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@selfmail-postgres:5432/${POSTGRES_DB}
      - POLAR_ACCESS_TOKEN=${POLAR_ACCESS_TOKEN}
      - TZ=${TZ}
    networks:
      - default

  smtp:
    build:
      context: .
      dockerfile: apps/smtp/Dockerfile
    container_name: selfmail-smtp
    restart: unless-stopped
    ports:
      - "25:25"   # SMTP inbound
      - "587:587" # SMTP outbound (submission)
    depends_on:
      - redis
      - rspamd
      - clamav
    environment:
      - NODE_ENV=production
      - REDIS_HOST=selfmail-redis
      - REDIS_PORT=6379
      - RSPAMD_HOST=rspamd
      - RSPAMD_PORT=11332
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
      - TZ=${TZ}
    networks:
      - default
    # Required for binding to privileged ports
    privileged: false
    cap_add:
      - NET_BIND_SERVICE

  relay:
    build:
      context: .
      dockerfile: apps/relay/Dockerfile
    container_name: selfmail-relay
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - queue
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_HOST=selfmail-redis
      - REDIS_PORT=6379
      - TZ=${TZ}
    networks:
      - default

  smtp-api:
    build:
      context: .
      dockerfile: apps/smtp-api/Dockerfile
    container_name: selfmail-smtp-api
    restart: unless-stopped
    ports:
      - "4001:4001"
    depends_on:
      - redis
      - postgres
      - clamav
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@selfmail-postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=selfmail-redis
      - REDIS_PORT=6379
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
      - TZ=${TZ}
    networks:
      - default

  transactional-queue:
    build:
      context: .
      dockerfile: apps/transactional-queue/Dockerfile
    container_name: selfmail-transactional-queue
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=selfmail-redis
      - REDIS_PORT=6379
      - TZ=${TZ}
    networks:
      - default

volumes:
  postgres_data:
  redis_data: