version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: selfmail
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: