services:
  rspamd:
    image: rspamd/rspamd:latest
    container_name: rspamd
    restart: unless-stopped
    ports:
      - "11332:11332" # Proxy/Milter
      - "11333:11333" # HTTP/JSON API
      - "11334:11334" # Web UI
    volumes:
      - ./rspamd/etc:/etc/rspamd
      - ./rspamd/var:/var/lib/rspamd
    environment:
      - TZ=Europe/Berlin
  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    restart: unless-stopped
    ports:
      - "3310:3310"