FROM rabbitmq:3-management

# Download und installiere das delayed message exchange plugin
RUN apt-get update && apt-get install -y wget
RUN wget -O /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez

# Aktiviere die Plugins
RUN rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_delayed_message_exchange
