import "@/styles/globals.css";
// the ui style file, because without this, the styles won't working
import "ui/styles.css"
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { DialogProvider } from "ui"

export const metadata: Metadata = {
  title: "App | Selfmail",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <DialogProvider>
          {children}
        </DialogProvider>
      </body>
    </html>
  );
}
