/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as OtpIndexRouteImport } from './routes/otp/index'
import { Route as MagicLinkIndexRouteImport } from './routes/magic-link/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as RegisterSuccessIndexRouteImport } from './routes/register/success/index'
import { Route as OtpBackupCodesIndexRouteImport } from './routes/otp/backup-codes/index'
import { Route as LoginSuccessIndexRouteImport } from './routes/login/success/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpIndexRoute = OtpIndexRouteImport.update({
  id: '/otp/',
  path: '/otp/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkIndexRoute = MagicLinkIndexRouteImport.update({
  id: '/magic-link/',
  path: '/magic-link/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessIndexRoute = RegisterSuccessIndexRouteImport.update({
  id: '/register/success/',
  path: '/register/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpBackupCodesIndexRoute = OtpBackupCodesIndexRouteImport.update({
  id: '/otp/backup-codes/',
  path: '/otp/backup-codes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSuccessIndexRoute = LoginSuccessIndexRouteImport.update({
  id: '/login/success/',
  path: '/login/success/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact/': typeof ContactIndexRoute
  '/help/': typeof HelpIndexRoute
  '/login/': typeof LoginIndexRoute
  '/magic-link/': typeof MagicLinkIndexRoute
  '/otp/': typeof OtpIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/login/success/': typeof LoginSuccessIndexRoute
  '/otp/backup-codes/': typeof OtpBackupCodesIndexRoute
  '/register/success/': typeof RegisterSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/help': typeof HelpIndexRoute
  '/login': typeof LoginIndexRoute
  '/magic-link': typeof MagicLinkIndexRoute
  '/otp': typeof OtpIndexRoute
  '/register': typeof RegisterIndexRoute
  '/login/success': typeof LoginSuccessIndexRoute
  '/otp/backup-codes': typeof OtpBackupCodesIndexRoute
  '/register/success': typeof RegisterSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact/': typeof ContactIndexRoute
  '/help/': typeof HelpIndexRoute
  '/login/': typeof LoginIndexRoute
  '/magic-link/': typeof MagicLinkIndexRoute
  '/otp/': typeof OtpIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/login/success/': typeof LoginSuccessIndexRoute
  '/otp/backup-codes/': typeof OtpBackupCodesIndexRoute
  '/register/success/': typeof RegisterSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact/'
    | '/help/'
    | '/login/'
    | '/magic-link/'
    | '/otp/'
    | '/register/'
    | '/login/success/'
    | '/otp/backup-codes/'
    | '/register/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/help'
    | '/login'
    | '/magic-link'
    | '/otp'
    | '/register'
    | '/login/success'
    | '/otp/backup-codes'
    | '/register/success'
  id:
    | '__root__'
    | '/'
    | '/contact/'
    | '/help/'
    | '/login/'
    | '/magic-link/'
    | '/otp/'
    | '/register/'
    | '/login/success/'
    | '/otp/backup-codes/'
    | '/register/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MagicLinkIndexRoute: typeof MagicLinkIndexRoute
  OtpIndexRoute: typeof OtpIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  LoginSuccessIndexRoute: typeof LoginSuccessIndexRoute
  OtpBackupCodesIndexRoute: typeof OtpBackupCodesIndexRoute
  RegisterSuccessIndexRoute: typeof RegisterSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp/': {
      id: '/otp/'
      path: '/otp'
      fullPath: '/otp/'
      preLoaderRoute: typeof OtpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link/': {
      id: '/magic-link/'
      path: '/magic-link'
      fullPath: '/magic-link/'
      preLoaderRoute: typeof MagicLinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/success/': {
      id: '/register/success/'
      path: '/register/success'
      fullPath: '/register/success/'
      preLoaderRoute: typeof RegisterSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp/backup-codes/': {
      id: '/otp/backup-codes/'
      path: '/otp/backup-codes'
      fullPath: '/otp/backup-codes/'
      preLoaderRoute: typeof OtpBackupCodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/success/': {
      id: '/login/success/'
      path: '/login/success'
      fullPath: '/login/success/'
      preLoaderRoute: typeof LoginSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MagicLinkIndexRoute: MagicLinkIndexRoute,
  OtpIndexRoute: OtpIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  LoginSuccessIndexRoute: LoginSuccessIndexRoute,
  OtpBackupCodesIndexRoute: OtpBackupCodesIndexRoute,
  RegisterSuccessIndexRoute: RegisterSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
