export {
	createWorkspaceAddressFn,
	createWorkspaceDomainFn,
	deleteWorkspaceDomainFn,
	removeWorkspaceMemberFn,
	verifyWorkspaceDomainFn,
} from "./workspaces/mutations";
export {
	getAddressInboxFn,
	getDashboardEmailFn,
	getDashboardWorkspacesFn,
	getWorkspace,
	getWorkspaceAddressDomainsFn,
	getWorkspaceDomainsFn,
	getWorkspaceInboxFn,
	getWorkspaceMembersFn,
} from "./workspaces/queries";
export type {
	CreateWorkspaceAddressResult,
	DashboardAddress,
	DashboardAddressDomain,
	DashboardAddressInboxData,
	DashboardDomainDnsRecord,
	DashboardEmail,
	DashboardInboxData,
	DashboardWorkspace,
	DashboardWorkspaceDomain,
	DashboardWorkspaceDomainsData,
	DashboardWorkspaceMember,
	DashboardWorkspaceMembersData,
	DeleteWorkspaceDomainResult,
	WorkspaceDomainError,
	WorkspaceDomainResult,
	WorkspaceDomainSuccess,
} from "./workspaces/types";
