export {
  createWorkspaceAddressFn,
  createWorkspaceDomainFn,
  deleteWorkspaceDomainFn,
  deleteWorkspaceFn,
  removeWorkspaceMemberFn,
  updateWorkspaceSettingsFn,
  verifyWorkspaceDomainFn,
} from "./workspaces/mutations";
export {
  exportWorkspaceDataFn,
  getAddressInboxFn,
  getDashboardEmailFn,
  getDashboardWorkspacesFn,
  getInboxEmailPageFn,
  getWorkspace,
  getWorkspaceAddressDomainsFn,
  getWorkspaceDomainsFn,
  getWorkspaceInboxFn,
  getWorkspaceMembersFn,
  getWorkspaceSettingsFn,
} from "./workspaces/queries";
export type {
  CreateWorkspaceAddressResult,
  DashboardAddress,
  DashboardAddressDomain,
  DashboardAddressInboxData,
  DashboardDomainDnsRecord,
  DashboardEmail,
  DashboardEmailPage,
  DashboardInboxData,
  DashboardWorkspace,
  DashboardWorkspaceDomain,
  DashboardWorkspaceDomainsData,
  DashboardWorkspaceMember,
  DashboardWorkspaceMembersData,
  DashboardWorkspaceSettingsData,
  DeleteWorkspaceDomainResult,
  WorkspaceDataExport,
  WorkspaceDataExportResult,
  WorkspaceDomainError,
  WorkspaceDomainResult,
  WorkspaceDomainSuccess,
  WorkspaceSettingsResult,
} from "./workspaces/types";
