/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedOnboardingIndexRouteImport } from './routes/_authed/onboarding/index'
import { Route as AuthedWorkspaceSlugWorkspaceRouteImport } from './routes/_authed/$workspaceSlug/_workspace'
import { Route as AuthedWorkspaceSlugWorkspaceIndexRouteImport } from './routes/_authed/$workspaceSlug/_workspace/index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingIndexRoute = AuthedOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspaceSlugWorkspaceRoute =
  AuthedWorkspaceSlugWorkspaceRouteImport.update({
    id: '/$workspaceSlug/_workspace',
    path: '/$workspaceSlug',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedWorkspaceSlugWorkspaceIndexRoute =
  AuthedWorkspaceSlugWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkspaceSlugWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/$workspaceSlug': typeof AuthedWorkspaceSlugWorkspaceRouteWithChildren
  '/onboarding/': typeof AuthedOnboardingIndexRoute
  '/$workspaceSlug/': typeof AuthedWorkspaceSlugWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/onboarding': typeof AuthedOnboardingIndexRoute
  '/$workspaceSlug': typeof AuthedWorkspaceSlugWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/$workspaceSlug/_workspace': typeof AuthedWorkspaceSlugWorkspaceRouteWithChildren
  '/_authed/onboarding/': typeof AuthedOnboardingIndexRoute
  '/_authed/$workspaceSlug/_workspace/': typeof AuthedWorkspaceSlugWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$workspaceSlug' | '/onboarding/' | '/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/$workspaceSlug'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/'
    | '/_authed/$workspaceSlug/_workspace'
    | '/_authed/onboarding/'
    | '/_authed/$workspaceSlug/_workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/': {
      id: '/_authed/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthedOnboardingIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$workspaceSlug/_workspace': {
      id: '/_authed/$workspaceSlug/_workspace'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AuthedWorkspaceSlugWorkspaceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$workspaceSlug/_workspace/': {
      id: '/_authed/$workspaceSlug/_workspace/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof AuthedWorkspaceSlugWorkspaceIndexRouteImport
      parentRoute: typeof AuthedWorkspaceSlugWorkspaceRoute
    }
  }
}

interface AuthedWorkspaceSlugWorkspaceRouteChildren {
  AuthedWorkspaceSlugWorkspaceIndexRoute: typeof AuthedWorkspaceSlugWorkspaceIndexRoute
}

const AuthedWorkspaceSlugWorkspaceRouteChildren: AuthedWorkspaceSlugWorkspaceRouteChildren =
  {
    AuthedWorkspaceSlugWorkspaceIndexRoute:
      AuthedWorkspaceSlugWorkspaceIndexRoute,
  }

const AuthedWorkspaceSlugWorkspaceRouteWithChildren =
  AuthedWorkspaceSlugWorkspaceRoute._addFileChildren(
    AuthedWorkspaceSlugWorkspaceRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedWorkspaceSlugWorkspaceRoute: typeof AuthedWorkspaceSlugWorkspaceRouteWithChildren
  AuthedOnboardingIndexRoute: typeof AuthedOnboardingIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedWorkspaceSlugWorkspaceRoute:
    AuthedWorkspaceSlugWorkspaceRouteWithChildren,
  AuthedOnboardingIndexRoute: AuthedOnboardingIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
