/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedOnboardingIndexRouteImport } from './routes/_authed/onboarding/index'
import { Route as AuthedMailEmailIdRouteImport } from './routes/_authed/mail/$emailId'
import { Route as AuthedWorkspaceSlugWorkspaceRouteImport } from './routes/_authed/$workspaceSlug/_workspace'
import { Route as AuthedWorkspaceSlugWorkspaceIndexRouteImport } from './routes/_authed/$workspaceSlug/_workspace/index'
import { Route as AuthedWorkspaceSlugWorkspaceNewAddressRouteImport } from './routes/_authed/$workspaceSlug/_workspace/new-address'
import { Route as AuthedWorkspaceSlugWorkspaceAddressSlugRouteImport } from './routes/_authed/$workspaceSlug/_workspace/$addressSlug'
import { Route as AuthedWorkspaceSlugWorkspaceDomainsIndexRouteImport } from './routes/_authed/$workspaceSlug/_workspace/domains/index'
import { Route as AuthedWorkspaceSlugWorkspaceDomainsAddRouteImport } from './routes/_authed/$workspaceSlug/_workspace/domains/add'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingIndexRoute = AuthedOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMailEmailIdRoute = AuthedMailEmailIdRouteImport.update({
  id: '/mail/$emailId',
  path: '/mail/$emailId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspaceSlugWorkspaceRoute =
  AuthedWorkspaceSlugWorkspaceRouteImport.update({
    id: '/$workspaceSlug/_workspace',
    path: '/$workspaceSlug',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedWorkspaceSlugWorkspaceIndexRoute =
  AuthedWorkspaceSlugWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkspaceSlugWorkspaceRoute,
  } as any)
const AuthedWorkspaceSlugWorkspaceNewAddressRoute =
  AuthedWorkspaceSlugWorkspaceNewAddressRouteImport.update({
    id: '/new-address',
    path: '/new-address',
    getParentRoute: () => AuthedWorkspaceSlugWorkspaceRoute,
  } as any)
const AuthedWorkspaceSlugWorkspaceAddressSlugRoute =
  AuthedWorkspaceSlugWorkspaceAddressSlugRouteImport.update({
    id: '/$addressSlug',
    path: '/$addressSlug',
    getParentRoute: () => AuthedWorkspaceSlugWorkspaceRoute,
  } as any)
const AuthedWorkspaceSlugWorkspaceDomainsIndexRoute =
  AuthedWorkspaceSlugWorkspaceDomainsIndexRouteImport.update({
    id: '/domains/',
    path: '/domains/',
    getParentRoute: () => AuthedWorkspaceSlugWorkspaceRoute,
  } as any)
const AuthedWorkspaceSlugWorkspaceDomainsAddRoute =
  AuthedWorkspaceSlugWorkspaceDomainsAddRouteImport.update({
    id: '/domains/add',
    path: '/domains/add',
    getParentRoute: () => AuthedWorkspaceSlugWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/$workspaceSlug': typeof AuthedWorkspaceSlugWorkspaceRouteWithChildren
  '/mail/$emailId': typeof AuthedMailEmailIdRoute
  '/onboarding/': typeof AuthedOnboardingIndexRoute
  '/$workspaceSlug/$addressSlug': typeof AuthedWorkspaceSlugWorkspaceAddressSlugRoute
  '/$workspaceSlug/new-address': typeof AuthedWorkspaceSlugWorkspaceNewAddressRoute
  '/$workspaceSlug/': typeof AuthedWorkspaceSlugWorkspaceIndexRoute
  '/$workspaceSlug/domains/add': typeof AuthedWorkspaceSlugWorkspaceDomainsAddRoute
  '/$workspaceSlug/domains/': typeof AuthedWorkspaceSlugWorkspaceDomainsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/mail/$emailId': typeof AuthedMailEmailIdRoute
  '/onboarding': typeof AuthedOnboardingIndexRoute
  '/$workspaceSlug/$addressSlug': typeof AuthedWorkspaceSlugWorkspaceAddressSlugRoute
  '/$workspaceSlug/new-address': typeof AuthedWorkspaceSlugWorkspaceNewAddressRoute
  '/$workspaceSlug': typeof AuthedWorkspaceSlugWorkspaceIndexRoute
  '/$workspaceSlug/domains/add': typeof AuthedWorkspaceSlugWorkspaceDomainsAddRoute
  '/$workspaceSlug/domains': typeof AuthedWorkspaceSlugWorkspaceDomainsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/$workspaceSlug/_workspace': typeof AuthedWorkspaceSlugWorkspaceRouteWithChildren
  '/_authed/mail/$emailId': typeof AuthedMailEmailIdRoute
  '/_authed/onboarding/': typeof AuthedOnboardingIndexRoute
  '/_authed/$workspaceSlug/_workspace/$addressSlug': typeof AuthedWorkspaceSlugWorkspaceAddressSlugRoute
  '/_authed/$workspaceSlug/_workspace/new-address': typeof AuthedWorkspaceSlugWorkspaceNewAddressRoute
  '/_authed/$workspaceSlug/_workspace/': typeof AuthedWorkspaceSlugWorkspaceIndexRoute
  '/_authed/$workspaceSlug/_workspace/domains/add': typeof AuthedWorkspaceSlugWorkspaceDomainsAddRoute
  '/_authed/$workspaceSlug/_workspace/domains/': typeof AuthedWorkspaceSlugWorkspaceDomainsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceSlug'
    | '/mail/$emailId'
    | '/onboarding/'
    | '/$workspaceSlug/$addressSlug'
    | '/$workspaceSlug/new-address'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/domains/add'
    | '/$workspaceSlug/domains/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mail/$emailId'
    | '/onboarding'
    | '/$workspaceSlug/$addressSlug'
    | '/$workspaceSlug/new-address'
    | '/$workspaceSlug'
    | '/$workspaceSlug/domains/add'
    | '/$workspaceSlug/domains'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/'
    | '/_authed/$workspaceSlug/_workspace'
    | '/_authed/mail/$emailId'
    | '/_authed/onboarding/'
    | '/_authed/$workspaceSlug/_workspace/$addressSlug'
    | '/_authed/$workspaceSlug/_workspace/new-address'
    | '/_authed/$workspaceSlug/_workspace/'
    | '/_authed/$workspaceSlug/_workspace/domains/add'
    | '/_authed/$workspaceSlug/_workspace/domains/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/': {
      id: '/_authed/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthedOnboardingIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/mail/$emailId': {
      id: '/_authed/mail/$emailId'
      path: '/mail/$emailId'
      fullPath: '/mail/$emailId'
      preLoaderRoute: typeof AuthedMailEmailIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$workspaceSlug/_workspace': {
      id: '/_authed/$workspaceSlug/_workspace'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AuthedWorkspaceSlugWorkspaceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$workspaceSlug/_workspace/': {
      id: '/_authed/$workspaceSlug/_workspace/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof AuthedWorkspaceSlugWorkspaceIndexRouteImport
      parentRoute: typeof AuthedWorkspaceSlugWorkspaceRoute
    }
    '/_authed/$workspaceSlug/_workspace/new-address': {
      id: '/_authed/$workspaceSlug/_workspace/new-address'
      path: '/new-address'
      fullPath: '/$workspaceSlug/new-address'
      preLoaderRoute: typeof AuthedWorkspaceSlugWorkspaceNewAddressRouteImport
      parentRoute: typeof AuthedWorkspaceSlugWorkspaceRoute
    }
    '/_authed/$workspaceSlug/_workspace/$addressSlug': {
      id: '/_authed/$workspaceSlug/_workspace/$addressSlug'
      path: '/$addressSlug'
      fullPath: '/$workspaceSlug/$addressSlug'
      preLoaderRoute: typeof AuthedWorkspaceSlugWorkspaceAddressSlugRouteImport
      parentRoute: typeof AuthedWorkspaceSlugWorkspaceRoute
    }
    '/_authed/$workspaceSlug/_workspace/domains/': {
      id: '/_authed/$workspaceSlug/_workspace/domains/'
      path: '/domains'
      fullPath: '/$workspaceSlug/domains/'
      preLoaderRoute: typeof AuthedWorkspaceSlugWorkspaceDomainsIndexRouteImport
      parentRoute: typeof AuthedWorkspaceSlugWorkspaceRoute
    }
    '/_authed/$workspaceSlug/_workspace/domains/add': {
      id: '/_authed/$workspaceSlug/_workspace/domains/add'
      path: '/domains/add'
      fullPath: '/$workspaceSlug/domains/add'
      preLoaderRoute: typeof AuthedWorkspaceSlugWorkspaceDomainsAddRouteImport
      parentRoute: typeof AuthedWorkspaceSlugWorkspaceRoute
    }
  }
}

interface AuthedWorkspaceSlugWorkspaceRouteChildren {
  AuthedWorkspaceSlugWorkspaceAddressSlugRoute: typeof AuthedWorkspaceSlugWorkspaceAddressSlugRoute
  AuthedWorkspaceSlugWorkspaceNewAddressRoute: typeof AuthedWorkspaceSlugWorkspaceNewAddressRoute
  AuthedWorkspaceSlugWorkspaceIndexRoute: typeof AuthedWorkspaceSlugWorkspaceIndexRoute
  AuthedWorkspaceSlugWorkspaceDomainsAddRoute: typeof AuthedWorkspaceSlugWorkspaceDomainsAddRoute
  AuthedWorkspaceSlugWorkspaceDomainsIndexRoute: typeof AuthedWorkspaceSlugWorkspaceDomainsIndexRoute
}

const AuthedWorkspaceSlugWorkspaceRouteChildren: AuthedWorkspaceSlugWorkspaceRouteChildren =
  {
    AuthedWorkspaceSlugWorkspaceAddressSlugRoute:
      AuthedWorkspaceSlugWorkspaceAddressSlugRoute,
    AuthedWorkspaceSlugWorkspaceNewAddressRoute:
      AuthedWorkspaceSlugWorkspaceNewAddressRoute,
    AuthedWorkspaceSlugWorkspaceIndexRoute:
      AuthedWorkspaceSlugWorkspaceIndexRoute,
    AuthedWorkspaceSlugWorkspaceDomainsAddRoute:
      AuthedWorkspaceSlugWorkspaceDomainsAddRoute,
    AuthedWorkspaceSlugWorkspaceDomainsIndexRoute:
      AuthedWorkspaceSlugWorkspaceDomainsIndexRoute,
  }

const AuthedWorkspaceSlugWorkspaceRouteWithChildren =
  AuthedWorkspaceSlugWorkspaceRoute._addFileChildren(
    AuthedWorkspaceSlugWorkspaceRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedWorkspaceSlugWorkspaceRoute: typeof AuthedWorkspaceSlugWorkspaceRouteWithChildren
  AuthedMailEmailIdRoute: typeof AuthedMailEmailIdRoute
  AuthedOnboardingIndexRoute: typeof AuthedOnboardingIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedWorkspaceSlugWorkspaceRoute:
    AuthedWorkspaceSlugWorkspaceRouteWithChildren,
  AuthedMailEmailIdRoute: AuthedMailEmailIdRoute,
  AuthedOnboardingIndexRoute: AuthedOnboardingIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
