name: Types and Code Quality

on:
  push:
  pull_request:

jobs:
  code-quality:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun
      - name: Run Bun Install and Biome CI
        run: bun install && bunx biome ci apps packages scripts