name: Deploy main site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}