name: Deploy main site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
        working-directory: ./apps/www
      
      - name: Build
        run: bun run build
        working-directory: ./apps/www
      
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./apps/www